// Generated by LiveScript 1.2.0
(function(){
  var chokidar, watch;
  chokidar = require('chokidar');
  watch = function(full){
    full == null && (full = true);
    return function(cluster){
      var watcher;
      watcher = chokidar.watch(Object.keys(require.cache), {
        persistent: true
      });
      watcher.on('change', function(){
        return cluster.reload(full);
      });
      cluster.on('stop', function(){
        return watcher.close();
      });
      if (cluster.side === 'worker') {
        return cluster.send('watch', Object.keys(require.cache));
      } else if (cluster.side === 'master') {
        return cluster.on('message:watch', function(worker, msg){
          return watcher.add(msg);
        });
      }
    };
  };
  module.exports = watch;
}).call(this);
